### ISSUE TITLE
Kafka sink

### ISSUE THREAD

**Issue by mdemierre** [opsgenie/kubernetes-event-exporter#6]
As Kafka is commonly deployed in the enterprise, a Kafka sink would be really valuable.

Basics needed:

- Send JSON events to Kafka
- Sensible default producer configuration
- Support layout transformation (like Kinesis, SQS, ...)

Good to have:

- TLS authentication (for secured Kafka clusters)
- Async/sync producer 
- Delivery guarantee choice
- Full producer configuration
- Avro + Confluent Schema Registry support

I started already in a fork: https://github.com/opsgenie/kubernetes-event-exporter/compare/master...mdemierre:feature/receiver-kafka?expand=1

Please add if you have other requirements or opinions about the implementation.

**Comment by mustafaakin** [comment]
Kafka is really great and can be powerful with other integrations. Those requirements are more than enough as a starter though. Layout transformation would be really nice. We are still designing the batch API for high throughput environments, so I think it is better to use Kafka's async producer with non-batch sink implementation since sarama handles the batches? Correct me If I'm wrong.

**Comment by mdemierre** [comment]
Yes, it should work with the Async producer, but it handles batching and delivery itself in the background.

The Sync producer is less performant but would work better with the current API I think. This is because the `Send()` method of Sink is expected to return an error if the send failed. But with the Async producer, the errors come later through a channel (see the handlers in my draft implementation).

So unless I use the sync approach I can't really know when returning from Send() if there was an error. I could also listen to the channel right after sending, but it would be kinda equivalent to the Sync approach.

What do you think?
